<?php

namespace Proxies\__CG__\laguntzaile\BenevolesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personne extends \laguntzaile\BenevolesBundle\Entity\Personne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'nom', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'prenom', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'adresse', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'codePostal', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'ville', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'portable', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'domicile', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'email', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'dateNaissance', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'profession', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'competences', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'avatar', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'langues', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'commentaire');
        }

        return array('__isInitialized__', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'nom', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'prenom', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'adresse', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'codePostal', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'ville', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'portable', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'domicile', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'email', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'dateNaissance', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'profession', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'competences', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'avatar', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'langues', '' . "\0" . 'laguntzaile\\BenevolesBundle\\Entity\\Personne' . "\0" . 'commentaire');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', array($codePostal));

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', array());

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setPortable($portable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortable', array($portable));

        return parent::setPortable($portable);
    }

    /**
     * {@inheritDoc}
     */
    public function getPortable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPortable', array());

        return parent::getPortable();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicile($domicile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicile', array($domicile));

        return parent::setDomicile($domicile);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicile', array());

        return parent::getDomicile();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', array($dateNaissance));

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', array());

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession($profession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', array($profession));

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', array());

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompetences($competences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompetences', array($competences));

        return parent::setCompetences($competences);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompetences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompetences', array());

        return parent::getCompetences();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar($avatar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', array($avatar));

        return parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', array());

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setLangues($langues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLangues', array($langues));

        return parent::setLangues($langues);
    }

    /**
     * {@inheritDoc}
     */
    public function getLangues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLangues', array());

        return parent::getLangues();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire($commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', array($commentaire));

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', array());

        return parent::getCommentaire();
    }

}
